# Generated by Django 5.0.1 on 2024-02-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TB', 'tab'), ('LP', 'laptop'), ('PH', 'phone'), ('WT', 'watch'), ('TV', 'television'), ('CP', 'computer')], max_length=2),
        ),
    ]
